#!/usr/bin/env bash
riscv32-unknown-elf-as -o entry.o entry.s -march=rv32i
riscv32-unknown-elf-gcc -nostdlib -nostartfiles -c hello_world.c -march=rv32id -mstrict-align -fomit-frame-pointer
riscv32-unknown-elf-ld -o hello_world.elf entry.o hello_world.o -Tlink.ld 
riscv32-unknown-elf-objcopy hello_world.elf -O binary hello_world
