#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Dec 04 18:54:15 HKT 2024
# SW Build 3900603 on Fri Jun 16 19:30:25 MDT 2023
#
# IP Build 3900379 on Sat Jun 17 05:28:05 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim i2c_config_time_synth -key {Post-Synthesis:sim_1:Timing:i2c_config} -tclbatch i2c_config.tcl -log simulate.log"
xsim i2c_config_time_synth -key {Post-Synthesis:sim_1:Timing:i2c_config} -tclbatch i2c_config.tcl -log simulate.log

