#!/usr/bin/env bash
riscv32-none-elf-as -o entry.o entry.s -march=rv32i
riscv32-none-elf-gcc -nostdlib -nostartfiles -c game_of_life.c -march=rv32id
riscv32-none-elf-ld -o game_of_life.elf entry.o game_of_life.o -Tlink.ld 
riscv32-none-elf-objcopy game_of_life.elf -O binary game_of_life
